version: '3.9'
services:
  db-cressida:
    container_name: db-cressida
    image: postgres:alpine
    hostname: db-cressida
    environment:
      - POSTGRES_DB=${POSTGRESQL_NAME}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
    ports:
      - 127.0.0.1:{POSTGRESQL_PORT}:5432
    networks:
      - cressida

  app-cressida:
    container_name: app-cressida
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
    environment:
      - APP_PORT=${APP_PORT}
      - APP_HOST=${APP_HOST}
      - POSTGRESQL_NAME=${POSTGRESQL_NAME}
      - POSTGRESQL_PASS=${POSTGRESQL_PASS}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - APP_SECRET=${APP_SECRET}
      - OPENTELEMETRY_HOST=${OPENTELEMETRY_HOST}
      - OPENTELEMETRY_PORT=${OPENTELEMETRY_PORT}
    ports:
      - 4000:${APP_PORT}
    networks:
      - cressida
    depends_on:
      - db-cressida
      - jaeger-cressida

  jaeger-cressida:
    container_name: jaeger-cressida
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 9411:9411
      - 14269:14269
      - 14268:14268
      - 16686:16686
      - 5778:5778
      - 4317:4317
      - 4318:4318
    networks:
      - cressida

  prometheus-cressida:
    container_name: prometheus-cressida
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./infrastructure/config.yml:/etc/prometheus/prometheus.yml
    networks:
      - cressida

  grafana-cressida:
    container_name: grafana-cressida
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - cressida
    depends_on:
      - prometheus-cressida

networks:
  cressida:
    driver: bridge