version: '3.9'
services:
  db-cressida:
    container_name: db-cressida
    image: postgres:alpine
    hostname: db-cressida
    environment:
      - POSTGRES_DB=${POSTGRESQL_NAME}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASS}
    ports:
      - ${POSTGRESQL_PORT}:5432
    networks:
      - cressida

  app-cressida:
    container_name: app-cressida
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_SECRET=${SERVER_SECRET}
      - SERVER_URL_DOCS=${SERVER_URL_DOCS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OTLP_ENDPOINT=${OTLP_ENDPOINT}
      - POSTGRESQL_NAME=${POSTGRESQL_NAME}
      - POSTGRESQL_PASS=${POSTGRESQL_PASS}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
    ports:
      - 4000:${SERVER_PORT}
    networks:
      - cressida
    depends_on:
      - db-cressida
      - jaeger-cressida

  jaeger-cressida:
    container_name: jaeger-cressida
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 9411:9411
      - 14269:14269
      - 14268:14268
      - 16686:16686
      - 5778:5778
      - 4317:4317
      - 4318:4318
    networks:
      - cressida

  prometheus-cressida:
    container_name: prometheus-cressida
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./infrastructure/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cressida

  postgres-exporter:
    container_name: postgres-exporter
    image:  quay.io/prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_NAME=${DATA_SOURCE_NAME}
      - DATA_SOURCE_USER=${POSTGRESQL_USER}
      - DATA_SOURCE_PASS=${POSTGRESQL_PASS}
    depends_on:
      - db-cressida
    networks:
      - cressida

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node
    ports:
      - 9200:9100
    command: '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - cressida
    depends_on:
      - prometheus-cressida

  grafana-cressida:
    container_name: grafana-cressida
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - cressida
    volumes:
      - ./infrastructure/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus-cressida

networks:
  cressida:
    driver: bridge